### ISSUE TITLE
Uploading files, then editing metadata?

### ISSUE THREAD

**Issue by dave-mills** [stats4sd/SSD-Resources-Demo#12]
Could rework the upload resource process to have the file uploading first, which "initialises" the new resource.  Then user moves to the edit screen, which can be the same as the general "edit resource" screen.  

Thinking about it, the "initialise new resource" doesn't even need a file uploader - just needs the resource name / ID to create the folder.

**Comment by dave-mills** [comment]
Almost there with the new add/edit resource workflow on the front page...

**Comment by chrismclarke** [comment]
not all resources will have files so not sure how needed. Some workflow changes have been made so maybe revisit this later after more has settled.

**Comment by dave-mills** [comment]
No longer relevant - I think the 'add resource' workflow is pretty solid for the moment.
