### ISSUE TITLE
Make better use of primary index in resource names

### ISSUE THREAD

**Issue by chrismclarke** [stats4sd/SSD-Resources-Demo#14]
makes sense if resources held more meta in the name so that they can be queries quickly without having to navigate entire document.

e.g. resource at /resources/tags_collections_types_name or similar. 
that way could simply look for name contains 'rinstat' for everything related to name or tag

**Comment by dave-mills** [comment]
Hmmm, maybe.  Although I've just pushed my commits surrounding the "resource editor" element.  It now works in a similar way to the notes-app, so resource paths are `/resource/[[randomly-generated-id]]/data` . (check out the new resource tests in the database). 

I think this is more robust - less chance of problems with multiple users creating resources with the same name at the same time, etc etc.  

Does still leave the issue of making it easier to search.  Can we just have a search function that goes through the entire resource object?

**Comment by chrismclarke** [comment]
For the time being it seems easy enough to just query meta data in resource for search functionality. Fundamental problem also with renaming database key as meta changes (which it will), and preferable not to keep changing database. If the resource bank grows to sizes where current search no longer useful or too slow then we might instead want to look to elasticsearch of other systems instead of implementing our own. 

Closing for now.
