### ISSUE TITLE
Login, Add resource and Search element view conditions

### ISSUE THREAD

**Issue by chrismclarke** [stats4sd/SSD-Resources-Demo#40]
Need to put back login button, change the 'add resource' to only show if logged in and also change 'search' to only show from resources page (or bring up page when clicking from 'home').

**Comment by chrismclarke** [comment]
login back in

**Comment by dave-mills** [comment]
Add new resource also seems to show and hide based on logged in status, so nice one there.

**Comment by dave-mills** [comment]
Changed my mind - now both search and add new appear constantly in the header (for consistency).  The attached functions now just send the user to the resources page.

**Comment by chrismclarke** [comment]
I like it!
