### ISSUE TITLE
Prevent blank resource save and allow back navigation

### ISSUE THREAD

**Issue by chrismclarke** [stats4sd/SSD-Resources-Demo#42]
Still option to save blank resources, logic needs to be moved from 'back' button to 'save' button functions. Also need to modify back button behaviour to prompt discarding changes or turn into a cancel button

**Comment by chrismclarke** [comment]
fixed first part, back nav allowed but couldn't think of simple way to implement discard changes prompt (as not currently tracking whether changes have been made or not). Closing for now

**Comment by dave-mills** [comment]
For info - I setup change tracking via "pendingEdits" boolean and an observer on the resource object.
