### ISSUE TITLE
Clone firebase project and prepare for a 'live' version (with real resources)

### ISSUE THREAD

**Issue by dave-mills** [stats4sd/SSD-Resources-Demo#47]
Once we start having real resources, we'll need to have the development separated from the 'live' version.  This means a separate Firebase project so we don't accidentally delete our carefully uploaded real resources (with the current one moved to dev-resources.stats4sd.org or some-such nonsense). 

Unfortunately, it also means moving away from the master branch for development... 😯

**Comment by chrismclarke** [comment]
I was planning to create live resources from this version but can see why we would want a dev copy. I suggest we keep this for live this week, and once we have a few more resources make a clone (including current database). I’m pretty sure there are ways to automate database backups which could then be used within testing. Agreed moving away from master to dev branch.
