### ISSUE TITLE
On tag page, change edits to be "in-place"

### ISSUE THREAD

**Issue by dave-mills** [stats4sd/SSD-Resources-Demo#49]
For a better user experience when editing tags, replace the Tag editor card with a UI that lets you edit the tag object within the list. 

 - clicking the object will change the UI to show input elements in-place. 
 - changes will sync to database automatically, but original values will be kept in local storage to give the option to undo your changes. (Mainly to experiment with this style)
 - adding tags will be done with a + button at the bottom of the list.

**Comment by chrismclarke** [comment]
Not sure I exactly follow what’s going on here but I’m happy to wait and see what you come up with.
