### ISSUE TITLE
checkboxes display behind menu

### ISSUE THREAD

**Issue by chrismclarke** [stats4sd/SSD-Resources-Demo#5]
For a small subset of screen sizes.
due to stacking issues: https://github.com/PolymerElements/paper-dialog/issues/79
workaround might be defining fixed sizes/margins

**Comment by dave-mills** [comment]
In my latest commit I chose to ignore this issue and went with Iron-collapse elements (that way I could also keep the appearing checkboxes under the right title).

**Comment by chrismclarke** [comment]
I see what you did, nice. As it happens I fixed it by include a quick script that applies the fitInto property to stick it to the form (id=basic)

**Comment by chrismclarke** [comment]
...but then changed my mind and put in tabs...
