### ISSUE TITLE
Improve image choosing

### ISSUE THREAD

**Issue by dave-mills** [stats4sd/SSD-Resources-Demo#53]
Currently, resource-small chooses which image by checking for every standard resource type id within the `resource.rType`. If it finds one, it stops looking and returns the correct image. 

This works, but I can see it being a pain to update with new images / types in the future, and seems to bring my Chrome to the edge of crashing when running it locally. (no idea why - I don't think 10 x 10 sequential if-statements should break a browser... )

**Comment by chrismclarke** [comment]
The easy way to avoid if statements is a simple json lookup (id-key pairings). To make dynamic you would import this list from a db query, however I'm not convinced the 'proper flat way' is actually best in this situation. Flat works well to minimise requests over potentially large numbers of entries, however in our case the number of images is never going to grow too large, and it as they will most likely be cached offline with resources it makes sense to have them easily paired offline. I would therefore suggest doing similarly as I did with the attachment images, i.e.
-name images to match r-type text (either stripping special characters and whitespace, or creating some sort of slug for each r-type)
- throw them all in an r-type images folder
- tell the component to pull [rtype].jpg from the folder, with a fallback image if doesn't exist (using the image on-error function)

**Comment by chrismclarke** [comment]
implemented in v2 rewrite. closing
