### ISSUE TITLE
Create new tags directly from the resource editor

### ISSUE THREAD

**Issue by dave-mills** [stats4sd/SSD-Resources-Demo#54]
Would be great to be able to create a new tag from within the resource editor itself, so users don't need to break their workflow when they discover a missing tag.

**Comment by chrismclarke** [comment]
Nearly complete, have had to give quite an overhaul of the current system (recreating most of paper-tags element as it was proving tricky to configure correctly). Demo working for Resource-Type tags, now just need to generalise and update display on other pages. d64beaca6eabb3ec785a3b572cf4b0ec590652f8 a59bfdd6b89f0c87a5945f4b0348947f9a201c6d
