### ISSUE TITLE
Deployed build still runs slowly - very slowly if you don't use Chrome.

### ISSUE THREAD

**Issue by dave-mills** [stats4sd/SSD-Resources-Demo#55]
Works a bit slow on Chrome. On other browsers an empty page is often shown for just long enough for me to start worrying it hasn't loaded.

**Comment by dave-mills** [comment]
*ahem*

Might have something to do with me trying to throw 2.6MB image files into every small-resource element.

No big deal, right?

**Comment by chrismclarke** [comment]
I've reduced images and will commit shortly, will look into issues more after

**Comment by chrismclarke** [comment]
noticeable improvement. Have also ran an audit with lighthouse (https://developers.google.com/web/tools/lighthouse/), which returned 33/100 - not abysmal but much room for improvement. The main issues seem to be with the service worker which is not registering correctly. Will investigate more...

**Comment by chrismclarke** [comment]
After playing around quite a bit with service workers from scratch I still couldn't quite get things working right (just wouldn't register), so reverting back to platinum-sw element but have left config files in -deprecated form. Will make an issue to revisit at a later date

**Comment by chrismclarke** [comment]
platinum was working in serve but still couldnt get to host, now back on custom but working (realised you need to specify -add-service-worker in polymer build). Should only have to do once unless modifying (I think...)

**Comment by chrismclarke** [comment]
up to 80/100... so better :D

**Comment by chrismclarke** [comment]
closing

**Comment by chrismclarke** [comment]
actually can still do more, continuing in new thread
