### ISSUE TITLE
Refresh on live site gives Firebase 404

### ISSUE THREAD

**Issue by dave-mills** [stats4sd/SSD-Resources-Demo#56]
To replicate: go to https://resources.stats4sd.org/resources. Then refresh page. 

For some reason it looks for an index at the subdirectory /resources, instead of applying the proper app-routing. 

Feels like some Firebase/polymer config setting we haven't set properly...

**Comment by chrismclarke** [comment]
quite possibly, I've tried adding some rewrites following this: http://stackoverflow.com/questions/41944147/page-refresh-returns-a-404error-with-polymer-firebase-cant-find-routed-page

Will try and test shortly

**Comment by chrismclarke** [comment]
yep, its fixed and deployed. closing
