### ISSUE TITLE
change layout of resources(full / edit)

### ISSUE THREAD

**Issue by dave-mills** [stats4sd/SSD-Resources-Demo#68]
For wide-screens - 2-column layout with resource bit (file, link, etc) on the right and details on the left.  

For smaller screens - resource bit on the top.

**Comment by chrismclarke** [comment]
guessing flex boxes should do this, or irons own flex element.
https://www.webcomponents.org/element/PolymerElements/iron-flex-layout.

(Does give warning message about deep deprecation however which is apparently fixed in version 2. Not sure if this is really a problem or not)

**Comment by chrismclarke** [comment]
Implemented
