### ISSUE TITLE
Deployed version unexpected token and general problems

### ISSUE THREAD

**Issue by chrismclarke** [stats4sd/SSD-Resources-Demo#7]
When the site is built with polymer build there are numerous problems, including not all components being copied (any that appear in index.html need to manually be added to include list), and the visited site has 'unexpected token' issues for various scripts (always first line, indicating it is something unclosed from a previous script).

For now simply changed firebase to deploy the entire folder, not just built, but should look to resolve in the future.

**Comment by dave-mills** [comment]
Exploring this with various build attempts. Currently getting many warnings when running polymer build.  Looks like it's being finicky about some syntax - the first warning went away after changing `for(let filter of filtersList)` to `for(var i=0; i<filtersList.length; i++)`.  Currently working through to make the other errors go away.

For reference - my original errors: 
```
warn:    Unable to optimize .js file /Users/dave/Documents/GitProjects/SSD-Resources-Demo/src/ssd-resources.html_script_0.js
{ err:
   { message: 'Unexpected token name «filter», expected punc «;»',
     filename: 0,
     line: 85,
     col: 17,
     pos: 2193 } }
warn:    Unable to optimize .html file /Users/dave/Documents/GitProjects/SSD-Resources-Demo/src/ssd-admin-tags.html
{ err: {} }
warn:    Unable to optimize .js file /Users/dave/Documents/GitProjects/SSD-Resources-Demo/src/SSD Components/ssd-resource-editor.html_script_0.js
{ err:
   { message: 'Unexpected token: name (res)',
     filename: 0,
     line: 77,
     col: 14,
     pos: 2199 } }
warn:    Unable to optimize .js file /Users/dave/Documents/GitProjects/SSD-Resources-Demo/src/SSD Components/ssd-resource-full.html_script_0.js
{ err:
   { message: 'Unexpected token: name (newResource)',
     filename: 0,
     line: 116,
     col: 14,
     pos: 3280 } }
warn:    Unable to optimize .js file /Users/dave/Documents/GitProjects/SSD-Resources-Demo/src/SSD Components/ssd-search.html_script_0.js
{ err:
   { message: 'Unexpected token: name (s)',
     filename: 0,
     line: 36,
     col: 12,
     pos: 897 } }
```

**Comment by chrismclarke** [comment]
Ah, that makes sense (my bad habit of using typescript instead of javascript and not transpiling). Option 1 is to change manually (probably easiest in short term), in longer term it would make sense to add a line to the build process to automatically compile javascript from higher level languages.

**Comment by dave-mills** [comment]
Mmm, makes sense.  The "let" statements are the main culprits - I guessed that was some fancy modern javascript thing. :-).

Manually editing for now. I'll let you mull over the possibilities of transpiling during build.

**Comment by dave-mills** [comment]
verbose errors on build fixed, hopefully without changing the functionality of those let commands. 

Current build is up on resources.stats4sd.org and seems to load/run quickly - though would be good to test properly on a poor internet connection.

**Comment by chrismclarke** [comment]
Amazing! (Also totally didn’t realise I could respond via email ☺ )

**Comment by chrismclarke** [comment]
can this now be closed @dave-mills ?
