### ISSUE TITLE
Non-chrome browsers broken in 0.9 live version (sorry!)

### ISSUE THREAD

**Issue by dave-mills** [stats4sd/SSD-Resources-Demo#88]
Looks like polyfills aren't working again.  On any browser other than Chrome, I can't get the site to load properly. Safari and Firefox  both give a set of recurring errors that slowly build and eat up my entire CPU after a few minutes

Firefox: 
- gives the error "Could not find style data in module named shared-styles" - polymer.html.js:2638:1
- also gives other "is undefined" errors, suggesting poly fills aren't loading properly. 
- can navigate from home to resources, but once loading resources page the page menu breaks (TypeError: Polymer.IronButtonStateImpl is undefined and a few other iron-element errors) 

The style data error occurs roughly once per second after loading resources page. If resources load at all, they display oddly.
![screenshot_115](https://cloud.githubusercontent.com/assets/5711101/26678089/bd74096a-46c6-11e7-8c4f-84ac8820afcb.png)

Safari: 
- simlar to above, except page menu sometimes continues to work after loading resources page.

**Comment by chrismclarke** [comment]
I'm hoping this is now fixed. It's a bit of a confusing mess with just how webcomponents need to be imported, particularly when there are several other ongoing imports, many of which are also asynchronous. Bizarrely I've found that importing webcomponents via a script code block as recommended actually breaks chrome but works in firefox so I've reverted back to pulling in via <script src=...>  (with an updated version of web components)

Many of these issues should be better resolved in polymer 2 (There's been lots of collaboration specifically with webcomponents), but for now @dave-mills could you test what I've pushed onto the demo server (https://ssd-resources-demo.firebaseapp.com) and let me know if working on safari? I've tested on firefox and chrome and both seem good.
