### ISSUE TITLE
Embed external url if youtube video

### ISSUE THREAD

**Issue by dave-mills** [stats4sd/SSD-Resources-Demo#90]
Would be good to include external links as clickable. If they're YouTube links, embedded video to get the bonus objective.

**Comment by dave-mills** [comment]
User error. Solved by realising I need to click the "+" button to actually save the url into the resource.

**Comment by chrismclarke** [comment]
Will work on youtube embed.

**Comment by chrismclarke** [comment]
implemented 7e0c06240fd9542c219e992b8014698f514a43b6
