### ISSUE TITLE
External Link field not emptied when creating new resource

### ISSUE THREAD

**Issue by dave-mills** [stats4sd/SSD-Resources-Demo#91]
When creating multiple resources in the same session, the external link box is pre-filled with the link entered into the previous resource. Probably just needs a variable emptying on load.

**Comment by dave-mills** [comment]
Not the issue I thought it was, (see #90 for my silliness), but this still stands. If I start a new resource, add a bunch of things, click back without saving, then go to add a new resource again, everything is emptied except the external link. 

Not sure if either everything should be emptied, or if everything should be as you left it from your 'incomplete / unsaved' resource.  @chrismclarke what do you think?

**Comment by chrismclarke** [comment]
I see the problem, everything else is populated from the resource (e.g. resource.description) which is cleaned on new init. This isn't possible for the new link as it is a nested property of an object that doesn't exist (e.g. resource.externalLinks[0].url). I've bound it to a temporary field on the resource itself which is then removed after save to mimic same behaviour (everything resets). In the future perhaps clicking back should save a draft resource which could be restored, but for now I think it's fine.
